// Run against an isolated --safe-mode backend, never a user's live runtime.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const base = process.env.HSCENTRIC_TEST_URL || 'http://127.0.0.1:17322';
const root = path.resolve(__dirname, '..');
const shots = path.join(root, '.impeccable', 'review');
const results = [];
const check = (name, condition) => { assert.ok(condition, name); results.push(name); };
let token;
async function api(route, method = 'GET', body, expected = 200, headers = {}) {
  const res = await fetch(base + '/api' + route, { method, headers: { 'Content-Type': 'application/json', 'X-HSCentric-Token': token || '', ...headers }, ...(body ? { body: JSON.stringify(body) } : {}) });
  const data = await res.json(); assert.equal(res.status, expected, `${method} ${route}: ${JSON.stringify(data)}`); return data;
}
const task = (start, stop, mode = '一条龙') => ({ mode, start, stop, teamName: '测试队伍', strategyName: 'PVE策略', map: '2-5', numCore: 2, numTotal: 6, scale: true, refreshQuest: true, claimAchievement: true, claimReward: true });
const account = (id, port, tasks) => ({ id, enable: false, hsPath: 'D:\\Hearthstone\\Hearthstone.exe', hbPath: '', hsModPort: port, token: 'synthetic-test-token', switchTask: false, tasks });
(async () => {
  const state = await api('/state'); check('test host is in safe mode', state.safeMode);
  check('test config starts empty', state.accounts.length === 0);
  token = (await api('/meta')).csrfToken;
  await api('/settings', 'PUT', { battleNetPath: '' }, 403, { 'X-HSCentric-Token': '' });
  await api('/settings', 'PUT', { battleNetPath: '' }, 403, { Origin: 'https://untrusted.example' });
  check('mutations reject missing CSRF and foreign origins', true);
  const leak = await fetch(base + '/HSCentric.exe.config'); check('configuration cannot be served as a static file', leak.status === 404);
  await api('/accounts', 'POST', account('重叠测试', 58740, [task('23:00', '02:00'), task('01:00', '03:00')]), 400);
  await api('/accounts', 'POST', account('重叠测试', 58740, [task('01:00', '03:00'), task('23:00', '02:00')]), 400);
  await api('/accounts', 'POST', account('相同时间', 58740, [task('08:00', '08:00')]), 400);
  check('overnight overlap rejected in either input order; equal endpoints rejected', true);
  await api('/accounts', 'POST', account('缺少时段', 58740, []), 400);
  await api('/accounts', 'POST', account('端口测试', 65536, [task('08:00', '09:00')]), 400);
  await api('/accounts', 'POST', account('模式测试', 58740, [task('08:00', '09:00', '未知')]), 400);
  await api('/accounts', 'POST', account('传统测试', 58740, [task('08:00', '09:00', '标准')]), 400);
  check('required tasks, port limits, modes, and Buddy prerequisites enforced', true);
  const first = await api('/accounts', 'POST', account('测试账号 · 晨间', 58741, [task('23:00', '02:00'), task('02:00', '08:00'), task('09:00', '12:00')]));
  check('adjacent and overnight tasks persist', first.tasks.length === 3);
  check('token is not returned to the browser', first.token === '');
  await api('/accounts', 'POST', account('测试账号 · 晨间', 58742, [task('08:00', '09:00')]), 409);
  await api('/accounts', 'POST', account('重复端口', 58741, [task('08:00', '09:00')]), 409);
  const route = '/accounts/' + encodeURIComponent(first.id);
  const changed = await api(route, 'PUT', { ...first, hsPath: 'D:\\HS\\Hearthstone.exe' });
  await api(route, 'PUT', first, 409);
  check('stale revisions and duplicate identifiers rejected', true);
  const runtimeDir = process.env.HSCENTRIC_TEST_RUNTIME_DIR || path.join(root, 'artifacts/backend');
  const config = fs.readFileSync(path.join(runtimeDir, 'HSCentric.exe.config'), 'utf8');
  check('blank token edit preserves stored secret', config.includes('synthetic-test-token'));
  await api(route + '/actions', 'POST', { action: 'start' }, 409);
  await api(route + '/actions', 'POST', { action: 'enable' });
  check('enable action reaches the real model', (await api(route)).enable);
  await api(route + '/actions', 'POST', { action: 'pause' });
  check('pause action disables account', !(await api(route)).enable);
  await api(route + '/actions', 'POST', { action: 'reset-xp' });
  check('safe mode blocks process launch and accepts configuration operations', true);
  await api('/accounts', 'POST', account('测试账号 · 收菜', 58742, [task('08:00', '18:00', '挂机收菜')]));
  const third = await api('/accounts', 'POST', account('测试账号 · 夜间', 58743, [task('18:00', '23:30', 'PVP')]));
  await api('/accounts/' + encodeURIComponent(third.id) + '/actions', 'POST', { action: 'enable' });
  const { chromium } = require('playwright');
  const browser = await chromium.launch({ channel: 'msedge', headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
  const errors = []; page.on('pageerror', e => errors.push(e.message)); page.on('console', m => { if (m.type() === 'error' && !m.text().includes('404')) errors.push(m.text()); });
  await page.goto(base); await page.getByText('后端已连接', { exact: true }).waitFor();
  check('three real accounts rendered', await page.locator('#account-rows tr').count() === 3);
  await page.getByRole('button', { name: '测试账号 · 收菜', exact: true }).click();
  await page.locator('#account-detail h2').filter({ hasText: '测试账号 · 收菜' }).waitFor();
  await page.getByRole('button', { name: '编辑配置', exact: true }).click();
  await page.locator('#account-dialog[open]').waitFor();
  await page.locator('[name="hsModPort"]').fill('65536');
  await page.getByRole('button', { name: '保存账号', exact: true }).click();
  check('native form validation blocks invalid port', await page.locator('#account-dialog').evaluate(el => el.open));
  await page.locator('[name="hsModPort"]').fill('58742');
  await page.getByRole('button', { name: '添加时段', exact: true }).click();
  await page.locator('#task-start').fill('19:00:00'); await page.locator('#task-stop').fill('21:00:00');
  await page.locator('#task-apply').click();
  await page.getByRole('button', { name: '保存账号', exact: true }).click();
  await page.locator('#account-dialog').waitFor({ state: 'hidden' });
  check('browser edits persist through API', (await api('/accounts/' + encodeURIComponent('测试账号 · 收菜'))).tasks.length === 2);
  await page.locator('.timeline .segment').first().click();
  await page.locator('#task-editor').waitFor({ state: 'visible' });
  check('timeline opens its corresponding task editor', await page.locator('#task-mode').inputValue() === '挂机收菜');
  await page.locator('#task-cancel').click(); await page.locator('#editor-close').click();
  await page.getByRole('button', { name: '编辑配置', exact: true }).click();
  await page.locator('[name="hsPath"]').fill('D:\\temporary-unsaved.exe');
  await page.locator('#editor-close').click(); await page.locator('#confirm-dialog[open]').waitFor();
  await page.locator('#confirm-dialog [value="cancel"]').click();
  check('cancel discard preserves draft input', await page.locator('[name="hsPath"]').inputValue() === 'D:\\temporary-unsaved.exe');
  await page.locator('#editor-close').click(); await page.locator('#confirm-accept').click();
  await page.getByRole('button', { name: '运行设置', exact: true }).click();
  await page.locator('#battle-net-path').fill('D:\\Battle.net\\Battle.net Launcher.exe');
  await page.getByRole('button', { name: '保存设置', exact: true }).click();
  await page.locator('#settings-dialog').waitFor({ state: 'hidden' });
  check('settings save through browser', (await api('/meta')).battleNetPath.includes('Launcher.exe'));
  await page.locator('#search').fill('无此账号'); await page.getByText('没有匹配的账号', { exact: true }).waitFor();
  await page.locator('#search').fill('');
  await page.locator('#log-pause').click(); check('log pause exposes its state', await page.locator('#log-pause').getAttribute('aria-pressed') === 'true');
  const download = page.waitForEvent('download'); await page.locator('#log-download').click(); check('log export produces a download', (await download).suggestedFilename().endsWith('.log'));
  fs.mkdirSync(shots, { recursive: true });
  await page.locator('#toast').waitFor({ state: 'hidden' });
  for (const [width, height, name] of [[1440,1000,'desktop'],[768,1000,'tablet'],[375,900,'mobile'],[320,900,'small-mobile']]) {
    await page.setViewportSize({ width, height }); await page.evaluate(() => window.scrollTo(0, 0));
    check(`no document overflow at ${width}px`, await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await page.screenshot({ path: path.join(shots, name + '.png'), fullPage: true });
  }
  await page.getByRole('button', { name: '编辑配置', exact: true }).click();
  check('mobile dialog stays inside viewport', await page.locator('#account-dialog').evaluate(el => { const r = el.getBoundingClientRect(); return r.left >= 0 && r.right <= innerWidth; }));
  await page.screenshot({ path: path.join(shots, 'mobile-editor.png'), fullPage: true });
  await page.keyboard.press('Escape');
  check('Escape closes an unchanged editor', !await page.locator('#account-dialog').evaluate(el => el.open));
  check('no browser JavaScript or CSP errors', errors.length === 0);
  await browser.close();
  fs.writeFileSync(path.join(shots, 'test-results.json'), JSON.stringify({ passed: results, consoleErrors: errors }, null, 2));
  process.stdout.write(JSON.stringify({ passed: results.length, checks: results }, null, 2) + '\n');
})().catch(error => { console.error(error); process.exit(1); });
